spring:
  application:
    name: graphqlgateway
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: storysizer
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: https://keycloak.public.cluster.local.com/realms/storysizer
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.public.cluster.local.com/realms/storysizer

  graphql:
    federation:
      services:
        stories: http://story-service.service-prod.svc.cluster.local:8080/graphql
        estimations: http://estimations-service.service-prod.svc.cluster.local:8081/graphql
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
server:
  port: 9090
  forward-headers-strategy: native
  error:
    include-stacktrace: always
