spring:
  application:
    name: graphqlgateway
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: storysizer
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: https://auth.storysizer.org/realms/storysizer
      resourceserver:
        jwt:
          issuer-uri: https://auth.storysizer.org/realms/storysizer

# --- CONFIGURAZIONE KICKSTART ---
graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: false          # stessa origin: CORS non necessario
  playground:
    enabled: false               # opzionale: spegne Playground
  graphiql:
    enabled: true
    mapping: /graphiql
    endpoint:
      graphql: /graphql          # a quale endpoint puntare
    cdn:
      enabled: false             # asset locali dal JAR (niente unpkg)
    props:
      variables:
        editorTheme: "dracula"   # opzionale, tema editor

server:
  port: 9090
  forward-headers-strategy: native

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

# Actuator endpoints for Kubernetes health probes
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true  # Enables /actuator/health/liveness and /actuator/health/readiness
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
