# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: frontend-dev
  name: jenkins-kubectl-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["delete", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["delete", "get", "list", "watch"]
