apiVersion: apps/v1
kind: Deployment
metadata:
  name: storysizer-web
  namespace: frontend-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storysizer-web
  template:
    metadata:
      labels:
        app: storysizer-web
    spec:
      containers:
      - name: storysizer-web
        image: fileini/storysizer-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: storysizer-web
  namespace: frontend-prod
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: storysizer-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storysizer-web-ingress
  namespace: frontend-prod
#  annotations:
#    traefik.ingress.kubernetes.io/router.middlewares: frontend-prod-spa-rewrite@kubernetescrd
spec:
  ingressClassName: traefik-public
  rules:
  - host: storysizer.public.cluster.local.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: storysizer-web
            port:
              number: 80
  tls:
  - hosts:
    - storysizer.public.cluster.local.com
    secretName: wildcard-public-cluster-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: spa-rewrite
  namespace: frontend-prod
spec:
  replacePathRegex:
    regex: "^/(.*)$"
    replacement: "/index.html"


