directive @key(fields: String!) on OBJECT | INTERFACE

type Query {
  stories: [Story]
  estimations: [Estimation]
  exportMyData: UserData
}

type Mutation {
  createStory(name: String!): Story
  createEstimation(
    name: String!,
    complexity: Int!,
    reach: Int!,
    dimensions: Int!,
    risk: Int!,
    interaction: Int!,
    storyId: String!
  ): Estimation
  deleteStory(id: ID!): Boolean
  deleteEstimation(id: ID!): Boolean
  deleteMyAccount: Boolean
}

type Story @key(fields: "id") {
  id: ID!
  name: String!
}

type Estimation @key(fields: "id") {
  id: ID!
  complexity: Int!
  reach: Int!
  story: Story!
  dimensions: Int!
  risk: Int!
  interaction: Int!
  sizer: Int
}

type UserData {
  stories: [Story]!
  estimations: [Estimation]!
}
