apiVersion: apps/v1
kind: Deployment
metadata:
  name: estimation-service
  namespace: service-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estimation-service
  template:
    metadata:
      labels:
        app: estimation-service
    spec:
      containers:
        - name: estimation-service
          image: fileini/estimation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: estimations-db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: estimation-service
  namespace: service-prod
spec:
  selector:
    app: estimation-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
