apiVersion: apps/v1
kind: Deployment
metadata:
  name: stories-service
  namespace: backend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stories-service
  template:
    metadata:
      labels:
        app: stories-service
    spec:
      containers:
        - name: stories-service
          image: stories-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: stories-db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: stories-service
  namespace: backend-dev
spec:
  selector:
    app: stories-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
